config/routes.rb
QScrape::Application.routes.draw do

  resources :brands
  resources :recipients
  resources :vehicles do
    post 'comment', on: :member
    get 'favor', on: :member
  end

  root :to => "vehicles#index"

end

app/models/recipient.rb
class Recipient < ActiveRecord::Base
end

app/controllers/recipients_controller.rb
class RecipientsController < ApplicationController
  # GET /recipients
  # GET /recipients.xml
  def index
    @recipients = Recipient.find(:all)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @recipients }
    end
  end

  # GET /recipients/1
  # GET /recipients/1.xml
  def show
    @recipient = Recipient.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @recipient }
    end
  end

  # GET /recipients/new
  # GET /recipients/new.xml
  def new
    @recipient = Recipient.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @recipient }
    end
  end

  # GET /recipients/1/edit
  def edit
    @recipient = Recipient.find(params[:id])
  end

  # POST /recipients
  # POST /recipients.xml
  def create
    @recipient = Recipient.new(params[:recipient])

    respond_to do |format|
      if @recipient.save
        flash[:notice] = 'Recipient was successfully created.'
        format.html { redirect_to(@recipient) }
        format.xml  { render :xml => @recipient, :status => :created, :location => @recipient }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @recipient.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /recipients/1
  # PUT /recipients/1.xml
  def update
    @recipient = Recipient.find(params[:id])

    respond_to do |format|
      if @recipient.update_attributes(params[:recipient])
        flash[:notice] = 'Recipient was successfully updated.'
        format.html { redirect_to(@recipient) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @recipient.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /recipients/1
  # DELETE /recipients/1.xml
  def destroy
    @recipient = Recipient.find(params[:id])
    @recipient.destroy

    respond_to do |format|
      format.html { redirect_to(recipients_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/recipients_helper.rb
module RecipientsHelper
end

app/views/recipients/edit.html.erb
<h1>Editing recipient</h1>

<% form_for(@recipient) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.submit "Update" %>
  </p>
<% end %>

<%= link_to 'Show', @recipient %> |
<%= link_to 'Back', recipients_path %>

app/views/recipients/index.html.erb
<h1>Listing recipients</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
  </tr>

<% for recipient in @recipients %>
  <tr>
    <td><%=h recipient.name %></td>
    <td><%=h recipient.email %></td>
    <td><%= link_to 'Show', recipient %></td>
    <td><%= link_to 'Edit', edit_recipient_path(recipient) %></td>
    <td><%= link_to 'Destroy', recipient, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New recipient', new_recipient_path %>

app/views/recipients/new.html.erb
<h1>New recipient</h1>

<% form_for(@recipient) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.submit "Create" %>
  </p>
<% end %>

<%= link_to 'Back', recipients_path %>

app/views/recipients/show.html.erb
<p>
  <b>Name:</b>
  <%=h @recipient.name %>
</p>

<p>
  <b>Email:</b>
  <%=h @recipient.email %>
</p>


<%= link_to 'Edit', edit_recipient_path(@recipient) %> |
<%= link_to 'Back', recipients_path %>