config/routes.rb
QScrape::Application.routes.draw do

  resources :brands
  resources :recipients
  resources :vehicles do
    post 'comment', on: :member
    get 'favor', on: :member
  end

  root :to => "vehicles#index"

end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
  belongs_to :source
  has_many :images
  belongs_to :brand
  
  attr_accessible :title, :url, :vtype, :location, :username, :timestamp, :contact_number, :contact_number2, :price, :model, :mileage, :description
  attr_accessible :class_name, :trim_name, :outside_color, :gear, :cylinders, :inside_color, :inside_type, :sunroof, :sensors, :camera, :dvd, :cd, :bluetooth, :gps
  attr_accessible :sid_i, :sid_s, :source_id, :duplicate_group, :brand_name

  # create view vehicles_dedup as select *, id as tid from vehicles;

  #self.table_name = 'qatarcars_copy'

  after_create do
    self.duplicate_group = self.id
    save
  end

  def opened?
    return (viewed_at != nil or notified_at != nil)
  end

  def find_by_largest_sid_i
    order("sid_i desc").first
  end

  def find_by_largest_sid_s
    order("sid_s desc").first
  end

  def find_by_smallest_sid_i
    order("sid_i asc").first
  end

  def find_by_smallest_sid_s
    order("sid_s asc").first
  end

  def duplicates
    return [] unless self.duplicate_group
    Vehicle.where(duplicate_group: self.duplicate_group)
  end

  def duplicates_count
    return 0 unless self.duplicate_group
    self.duplicates.count
  end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  # GET /vehicles
  # GET /vehicles.xml
  def index
    #@vehicles = Vehicle.find(:all, :limit => 20)
    conditions = []
    reset_page = false

    session[:filter] = params[:filter] if params[:filter] != nil
    @filter = session[:filter]

    if params[:toggle_favor] == 'on'
      reset_page = true if session[:favorites] == false
      session[:favorites] = true
    else
      reset_page = true if session[:favorites] == true
      session[:favorites] = false
    end
    
    if @filter and @filter != ''
      conditions = ["(title like :filter or description like :filter)", {:filter => "%#{@filter}%"}]
      reset_page = true
    end
    
    if params[:page]
      @page = params[:page]
    elsif reset_page
      @page = 1
    else
      @page = session[:page] || 1
    end
    session[:page] = @page
    
    @vehicles = Vehicle.where(conditions)
    @vehicles = @vehicles.where(:favorite => true) if session[:favorites]
    @vehicles = @vehicles.where(:duplicate_group => params[:duplicate_group]) if params[:duplicate_group]
    @page = 1 if params[:duplicate_group]
    @vehicles = @vehicles.order("id DESC").page(@page).per(25)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @vehicles }
    end
  end

  # GET /vehicles/1
  # GET /vehicles/1.xml
  def show
    @vehicle = Vehicle.find(params[:id])
    @vehicle.viewed_at = Time.now
    @vehicle.save

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @vehicle }
    end
  end

  def favor
    @vehicle = Vehicle.find(params[:id])
    @vehicle.favorite = ! @vehicle.favorite
    @vehicle.save

    respond_to do |format|
      format.html { render :action => "show"} # show.html.erb
      format.xml  { render :xml => @vehicle }
    end
  end
  
  def comment
    @vehicle = Vehicle.find(params[:id])
    @vehicle.comments = params[:text]
    @vehicle.save

    flash[:notice] = "Comment saved successfully"
    respond_to do |format|
      format.html { render :action => "show"} # show.html.erb
      format.xml  { render :xml => @vehicle }
    end
  end

end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/vehicles/edit.html.erb
<h1>Editing vehicle</h1>

<% form_for(@vehicle) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.submit "Update" %>
  </p>
<% end %>

<%= link_to 'Show', @vehicle %> |
<%= link_to 'Back', vehicles_path %>

app/views/vehicles/index.html.erb
<h1>Listing
<%if session[:favorites]%>
favorite
<%else%>
all
<%end%>
vehicles</h1>

<%= page_entries_info @vehicles %>

<div style="float: right">
  <form method="GET">
    <label for="filter">Search:</label>
    <input type=text id="filter" name="filter" value="<%=@filter%>"/>
    <input type=submit value="Go"/>
    <% if session[:favorites] %>
      <%= link_to 'Show all', :toggle_favor => 'off' %>
    <% else %>
      <%= link_to 'Show favorites', :toggle_favor => 'on' %>
    <% end %>
  </form>
</div>

<table width=100%>
  <tr>
    <td><b>Favorite?</b></td>
    <td><b>Duplicates</b></td>
    <td><b>Source</b></td>
    <td><b>Title</b></td>
    <td><b>Brand</b></td>
    <td><b>Model</b></td>
    <td><b>Mileage</b></td>
    <td><b>Price</b></td>
    <td><b>External link</b></td>
  </tr>

<% for vehicle in @vehicles %>
  <tr <%= "class=vehicle-row-new" if not vehicle.opened?%> >
    <td>
      <%='YES' if vehicle.favorite %>
    </td>
    <td>
      <%= link_to (vehicle.duplicate_group ? vehicle.duplicates_count : '-'), vehicles_path + "?duplicate_group=#{vehicle.duplicate_group}" %>
    </td>
    <td>
      <%= vehicle.source %>
    </td>
    <td>
      <a href="/vehicles/<%=vehicle.id%>"><%=vehicle.title%></a>
    </td>
    <td><%= vehicle.brand_name %></td>
    <td><%= vehicle.model %></td>
    <td><%= vehicle.mileage %></td>
    <td><%= vehicle.price %></td>
    <td><a target="_blank" href="<%=vehicle.url%>">Goto</a></td>
  </tr>
<% end %>
</table>
<center>
<%= paginate @vehicles %>
</center>
<br />

<script>
  document.getElementById('filter').focus()
</script>

app/views/vehicles/new.html.erb
<h1>New vehicle</h1>

<% form_for(@vehicle) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.submit "Create" %>
  </p>
<% end %>

<%= link_to 'Back', vehicles_path %>

app/views/vehicles/show.html.erb
<script type="text/javascript">
  function saveComment() {
    document.getElementById('commentsForm').submit()
    return false
  }
  function removeComment() {
    document.getElementById('commentsText').value = ''
    document.getElementById('commentsForm').submit()
    return false
  }
</script>

<h1>
<%=@vehicle.title%>
[<a target="_blank" href="<%=@vehicle.url%>">Goto</a>]
</h1>

<div style="float: right">
  <% @vehicle.images.each do |image| %>
    <div>
      <img src="<%=image.url%>"/>
    </div>
  <% end %>
</div>

<h3><b>Submitted at:</b> <%=@vehicle.timestamp%></h3>

<p>
<b>Brand:</b> <%=@vehicle.brand_name%> <%= @vehicle.class_name %> <%= @vehicle.trim_name %> &nbsp;&nbsp;
<b>Model:</b> <%=@vehicle.model%> &nbsp;&nbsp;
<b>Mileage:</b> <%=@vehicle.mileage%>
</p>

<p>
<b>Price:</b> <%=@vehicle.price%> &nbsp;&nbsp;&nbsp;
<b>Contact number(s):</b> <%=[@vehicle.contact_number, @vehicle.contact_number2].compact.join(', ')%> &nbsp;&nbsp;&nbsp;
<b>Vehicle type:</b> <%=@vehicle.vtype%>
</p>

<p>
<b>Location:</b> <%=@vehicle.location%> &nbsp;&nbsp;
<b>Seller:</b> <%= @vehicle.username %>
</p>

<p>
<b>Specs:</b>
<ul>
  <li>Outside color: <%= @vehicle.outside_color.nil? ? 'N/A' : @vehicle.outside_color %></li>
  <li>Gear: <%= @vehicle.gear.nil? ? 'N/A' : @vehicle.gear %></li>
  <li>Cylinders: <%= @vehicle.cylinders.nil? ? 'N/A' : @vehicle.cylinders %></li>
  <li>Inside color: <%= @vehicle.inside_color.nil? ? 'N/A' : @vehicle.inside_color %></li>
  <li>Inside type: <%= @vehicle.inside_type.nil? ? 'N/A' : @vehicle.inside_type %></li>
  <li>Sunroof: <%= @vehicle.sunroof.nil? ? 'N/A' : (@vehicle.sunroof ? 'Yes' : 'No') %></li>
  <li>Sensors: <%= @vehicle.sensors.nil? ? 'N/A' : (@vehicle.sensors ? 'Yes' : 'No') %></li>
  <li>Camera: <%= @vehicle.camera.nil? ? 'N/A' : (@vehicle.camera ? 'Yes' : 'No') %></li>
  <li>DVD: <%= @vehicle.dvd.nil? ? 'N/A' : (@vehicle.dvd ? 'Yes' : 'No') %></li>
  <li>CD: <%= @vehicle.cd.nil? ? 'N/A' : (@vehicle.cd ? 'Yes' : 'No') %></li>
  <li>Bluetooth: <%= @vehicle.bluetooth.nil? ? 'N/A' : (@vehicle.bluetooth ? 'Yes' : 'No') %></li>
  <li>GPS: <%= @vehicle.gps.nil? ? 'N/A' : (@vehicle.gps ? 'Yes' : 'No') %></li>
</ul>
</p>

<p>
  <b>Description:</b> <br/>
  <%=@vehicle.description.html_safe rescue 'None' %>
</p>
<p>
  <b>Comments:</b>
  <a href="#" onclick="return saveComment()">Save</a>
  -
  <a href="#" onclick="return removeComment()">Remove</a>
  <br/>
  <%= form_for @vehicle, method: "POST", url: comment_vehicle_path(@vehicle), html: {id: 'commentsForm'} do |f| %>
    <textarea id="commentsText" name="text" rows=2 cols=120><%=@vehicle.comments%></textarea>
  <% end %>
</p>

<h3>
<%if @vehicle.favorite%>
  <%= link_to 'Remove from favorites', favor_vehicle_path(@vehicle) %>
<%else%>
  <%= link_to 'Add to favorites', favor_vehicle_path(@vehicle) %>
<%end%>

</h3>

<%= link_to 'Back', :action => 'index' %>